# -*- coding: utf-8 -*-
"""DSCI 511_Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFxT8TpmxJnz1lprcrd2Z8iIUvhlqWSo
"""

#! usr/bin/env python3
import praw
import pandas as pd
import datetime as dt
from pprint import pprint

reddit = praw.Reddit(client_id='A9UAtvollb2rLg', \
                     client_secret='VXw8b4vjjoA_jybYNpTgNC2mHQE', \
                     user_agent='ScrapeSubReddit', \
                     username='smpascua', \
                     password='Kanchi123')

subreddit = reddit.subreddit('MoneyDiariesACTIVE')

print(subreddit)

top_subreddit = subreddit.top(limit=100)

print(top_subreddit)

topics_dict = {"url":[]}

for submission in top_subreddit:
    topics_dict["url"].append(submission.url)

print(topics_dict)

pprint(topics_dict)

topics_data = pd.DataFrame(topics_dict)

pprint(topics_data)

def get_date(created):
    return dt.datetime.fromtimestamp(created)

topics_data.to_csv('FILENAME.csv', index=False)