# -*- coding: utf-8 -*-
"""DSCI 511_Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFxT8TpmxJnz1lprcrd2Z8iIUvhlqWSo
"""

#! usr/bin/env python3
import praw
import pandas as pd
import datetime as dt
from pprint import pprint
import json

#pip install praw

reddit = praw.Reddit(client_id='A9UAtvollb2rLg', \
                     client_secret='VXw8b4vjjoA_jybYNpTgNC2mHQE', \
                     user_agent='ScrapeSubReddit', \
                     username='smpascua', \
                     password='Kanchi123')
subreddit = reddit.subreddit('MoneyDiariesACTIVE')
#print(subreddit)
top_subreddit = subreddit.top(limit=100)
#dictionary for the data
topics_dict = {"url":[], "title":[], "id":[], "comments":[], "comments_level1":[], "body":[]}
for element in top_subreddit:
  if '/comments' in element.url:
    topics_dict["url"].append(element.url)
    topics_dict["title"].append(element.title)
    topics_dict["id"].append(element.id)
    topics_dict["comments"].append(element.comments)
    for comments_level1 in element.comments:
      topics_dict["comments_level1"].append(comments_level1.body + "")
      #print(comments_level1.body)
      break
    topics_dict["body"].append(element.selftext)
print(topics_dict)

pprint(topics_dict)

topics_data = pd.DataFrame.from_dict(topics_dict, orient='index')
topics_data.transpose()

topics_data.to_csv('Subreddit_MoneyDiariesActive.csv', index=False)

df = topics_data.to_json()
with open('Subreddit_MoneyDiariesActive.json', 'w') as json_file:
  json.dump(df, json_file)
