# -*- coding: utf-8 -*-
"""DSCI 511_Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFxT8TpmxJnz1lprcrd2Z8iIUvhlqWSo
"""

#! usr/bin/env python3
import praw
import pandas as pd
import datetime as dt
from pprint import pprint

reddit = praw.Reddit(client_id='A9UAtvollb2rLg', \
                     client_secret='VXw8b4vjjoA_jybYNpTgNC2mHQE', \
                     user_agent='ScrapeSubReddit', \
                     username='smpascua', \
                     password='Kanchi123')
subreddit = reddit.subreddit('MoneyDiariesACTIVE')
#print(subreddit)
top_subreddit = subreddit.top(limit=100)
#print(top_subreddit)
topics_dict = {"url":[], "title":[], "id":[], "comments":[], "comments_level1":[], "body":[]}
for submission in top_subreddit:
  if '/comments' in submission.url:
    topics_dict["url"].append(submission.url)
    topics_dict["title"].append(submission.title)
    topics_dict["id"].append(submission.id)
    topics_dict["comments"].append(submission.comments)
    for comments_level1 in submission.comments:
      topics_dict["comments_level1"].append(comments_level1.body + "")
      #print(comments_level1.body)
      break
    topics_dict["body"].append(submission.selftext)
print(topics_dict)

print(topics_dict)

pprint(topics_dict)

topics_data = pd.DataFrame(topics_dict)

pprint(topics_data)

def get_date(created):
    return dt.datetime.fromtimestamp(created)

topics_data.to_csv('FILENAME.csv', index=False)
